export const INTEGRATIONS_CONFIG = {
    PAYPAL_CLIENT_ID: "ATF81uitzRR35l2wFyTxBmEg01TOTGW6Ftn7oUIkGdcdCBdDknTei-dyFfWlMWUit6k-3j4137t-8E7b",
    STRIPE_PUBLISHABLE_KEY: import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY
};  